### ISSUE TITLE
breaks on documentation-tag in wsdl operation

### ISSUE THREAD

**Issue by hedefalk** [eed3si9n/scalaxb#248]
Originally reported as https://groups.google.com/forum/#!topic/scalaxb/_B4d6mWnLn0
## problem

```
> last compile:scalaxb 
scalaxb.ParserFailure: Error while parsing <operation 
name="getValidCodes" xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:tns="http://service.linkon.se/gtssales/v1_14" 
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns="http://schemas.xmlsoap.org/wsdl/"> 
<soap:operation soapAction=""/> 
<documentation> 
The operation returns the valid (relevant) code lists 
for this service. 
</documentation> 
<input> 
<soap:header use="literal" part="clientInformationHeader" 
message="tns:WSGtsSales_getValidCodeRequest"/> 
<soap:body use="literal" parts="parameters"/> 
</input> 
<output> 
<soap:header use="literal" part="serverInformationHeader" 
message="tns:ServerInformation"/> 
<soap:body use="literal"/> 
</output> 
<fault name="GtsSalesException"> 
<soap:fault use="literal" name="GtsSalesException"/> 
</fault> 
</operation>: parser error "`{http://schemas.xmlsoap.org/wsdl/}fault' 
expected but {http://schemas.xmlsoap.org/wsdl/}documentation found" 
while parsing /{http://schemas.xmlsoap.org/wsdl/}definitions/{http://schemas.xmlsoap.org/wsdl/}binding/{http://schemas.xmlsoap.org/wsdl/}operation/{http://schemas.xmlsoap.org/wsdl/soap/}operation{http://schemas.xmlsoap.org/wsdl/}documentation{http://schemas.xmlsoap.org/wsdl/}input{http://schemas.xmlsoap.org/wsdl/}output{http://schemas.xmlsoap.org/wsdl/}fault 
 ^ 
at scalaxb.package$.fromXML(scalaxb.scala:15) 
at wsdl11.XXMLProtocol$DefaultWsdl11XBindingTypeFormat$$anonfun$parser$33$$anonfun$apply$59.apply(wsdl11_xmlprotocol.scala:437) 
at wsdl11.XXMLProtocol$DefaultWsdl11XBindingTypeFormat$$anonfun$parser$33$$anonfun$apply$59.apply(wsdl11_xmlprotocol.scala:437) 
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) 
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) 
at scala.collection.immutable.List.foreach(List.scala:318) 
at scala.collection.TraversableLike$class.map(TraversableLike.scala:244) 
at scala.collection.AbstractTraversable.map(Traversable.scala:105) 
at wsdl11.XXMLProtocol$DefaultWsdl11XBindingTypeFormat$$anonfun$parser$33.apply(wsdl11_xmlprotocol.scala:437) 
at wsdl11.XXMLProtocol$DefaultWsdl11XBindingTypeFormat$$anonfun$parser$33.apply(wsdl11_xmlprotocol.scala:434) 
at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:136) 
at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:135) 
at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242) 
at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242) 
at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222) 
at scala.util.parsing.combinator.Parsers$$anon$2$$anonfun$apply$14.apply(Parsers.scala:891) 
at scala.util.parsing.combinator.Parsers$$anon$2$$anonfun$apply$14.apply(Parsers.scala:891) 
at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57) 
at scala.util.parsing.combinator.Parsers$$anon$2.apply(Parsers.scala:890) 
at scalaxb.ElemNameParser$class.parse(scalaxb.scala:679) 
at wsdl11.XXMLProtocol$$anon$12.parse(wsdl11_xmlprotocol.scala:30) 
at scalaxb.ElemNameParser$class.reads(scalaxb.scala:659) 
```

**Comment by oumsofiane1** [comment]
Just a note, this work around may not work if you are trying to mock a service and you already have an existing client relying on the WSDL specification.
