### ISSUE TITLE
Parser error "`{http://schemas.xmlsoap.org/wsdl/}fault' expected but {http://schemas.xmlsoap.org/wsdl/}documentation found"

### ISSUE THREAD

**Issue by AmirKarimi** [eed3si9n/scalaxb#300]
I get the following error when trying to generate files from [this WSDL file](https://gist.github.com/AmirKarimi/593336b87969bfa8b62c).

Here the command:
```
scalaxb novinpyamak.wsdl -p novinpayamak -d ./src/main/scala --package-dir
```
Scalaxb version is 1.3.0

```
masked.scalaxb.ParserFailure: Error while parsing <wsdl:operation name="Send" xmlns:tns="http://SMSBox.gateway.webservice.sspk.co.ir/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
        <soap:operation style="document" soapAction="#Send"/>
        <wsdl:input><soap:body use="literal"/></wsdl:input>
        <wsdl:output><soap:body use="literal"/></wsdl:output>
        <wsdl:documentation>Send batch SMS by using this method</wsdl:documentation>
    </wsdl:operation>: parser error "`{http://schemas.xmlsoap.org/wsdl/}fault' expected but {http://schemas.xmlsoap.org/wsdl/}documentation found" while parsing /{http://schemas.xmlsoap.org/wsdl/}definitions/{http://schemas.xmlsoap.org/wsdl/}binding/{http://schemas.xmlsoap.org/wsdl/}operation/{http://schemas.xmlsoap.org/wsdl/soap/}operation{http://schemas.xmlsoap.org/wsdl/}input{http://schemas.xmlsoap.org/wsdl/}output{http://schemas.xmlsoap.org/wsdl/}documentation
   ^
	at masked.scalaxb.package$.fromXML(scalaxb.scala:17)
	at wsdl11.XXMLProtocol$DefaultWsdl11XBindingTypeFormat$$anonfun$parser$33$$anonfun$apply$59.apply(wsdl11_xmlprotocol.scala:439)
	at wsdl11.XXMLProtocol$DefaultWsdl11XBindingTypeFormat$$anonfun$parser$33$$anonfun$apply$59.apply(wsdl11_xmlprotocol.scala:439)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at wsdl11.XXMLProtocol$DefaultWsdl11XBindingTypeFormat$$anonfun$parser$33.apply(wsdl11_xmlprotocol.scala:439)
	at wsdl11.XXMLProtocol$DefaultWsdl11XBindingTypeFormat$$anonfun$parser$33.apply(wsdl11_xmlprotocol.scala:436)
	at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:136)
	at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:135)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.Parsers$$anon$2$$anonfun$apply$14.apply(Parsers.scala:891)
	at scala.util.parsing.combinator.Parsers$$anon$2$$anonfun$apply$14.apply(Parsers.scala:891)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
	at scala.util.parsing.combinator.Parsers$$anon$2.apply(Parsers.scala:890)
	at masked.scalaxb.ElemNameParser$class.parse(scalaxb.scala:713)
	at wsdl11.XXMLProtocol$$anon$12.parse(wsdl11_xmlprotocol.scala:32)
	at masked.scalaxb.ElemNameParser$class.reads(scalaxb.scala:693)
	at wsdl11.XXMLProtocol$$anon$12.reads(wsdl11_xmlprotocol.scala:32)
	at masked.scalaxb.package$.fromXML(scalaxb.scala:15)
	at wsdl11.XXMLProtocol$DefaultWsdl11XDefinitionsTypeFormat$$anonfun$parser$5$$anonfun$apply$8$$anonfun$apply$16$$anonfun$apply$17.apply(wsdl11_xmlprotocol.scala:155)
	at wsdl11.XXMLProtocol$DefaultWsdl11XDefinitionsTypeFormat$$anonfun$parser$5$$anonfun$apply$8$$anonfun$apply$16$$anonfun$apply$17.apply(wsdl11_xmlprotocol.scala:155)
	at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:136)
	at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:135)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.Parsers$Parser$$anon$4.apply(Parsers.scala:349)
	at scala.util.parsing.combinator.Parsers$Parser$$anon$4.apply(Parsers.scala:348)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.Parsers$$anonfun$rep1$1.applyp$1(Parsers.scala:727)
	at scala.util.parsing.combinator.Parsers$$anonfun$rep1$1.continue$1(Parsers.scala:733)
	at scala.util.parsing.combinator.Parsers$$anonfun$rep1$1.apply(Parsers.scala:737)
	at scala.util.parsing.combinator.Parsers$$anonfun$rep1$1.apply(Parsers.scala:721)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.Parsers$Success.flatMapWithNext(Parsers.scala:142)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:239)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:239)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
	at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
	at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
	at scala.util.parsing.combinator.Parsers$$anon$2$$anonfun$apply$14.apply(Parsers.scala:891)
	at scala.util.parsing.combinator.Parsers$$anon$2$$anonfun$apply$14.apply(Parsers.scala:891)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
	at scala.util.parsing.combinator.Parsers$$anon$2.apply(Parsers.scala:890)
	at masked.scalaxb.ElemNameParser$class.parse(scalaxb.scala:713)
	at wsdl11.XXMLProtocol$$anon$3.parse(wsdl11_xmlprotocol.scala:21)
	at masked.scalaxb.ElemNameParser$class.reads(scalaxb.scala:693)
	at wsdl11.XXMLProtocol$$anon$3.reads(wsdl11_xmlprotocol.scala:21)
	at masked.scalaxb.package$.fromXML(scalaxb.scala:15)
	at scalaxb.compiler.wsdl11.Driver$$anon$5.x$10$lzycompute(Driver.scala:134)
	at scalaxb.compiler.wsdl11.Driver$$anon$5.x$10(Driver.scala:132)
	at scalaxb.compiler.wsdl11.Driver$$anon$5.wsdl$lzycompute(Driver.scala:132)
	at scalaxb.compiler.wsdl11.Driver$$anon$5.wsdl(Driver.scala:132)
	at scalaxb.compiler.wsdl11.Driver$$anon$5.<init>(Driver.scala:159)
	at scalaxb.compiler.wsdl11.Driver.toImportable(Driver.scala:125)
	at scalaxb.compiler.wsdl11.Driver.toImportable(Driver.scala:35)
	at scalaxb.compiler.Module$$anonfun$2.apply(Module.scala:233)
	at scalaxb.compiler.Module$$anonfun$2.apply(Module.scala:232)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at scalaxb.compiler.Module$class.buildCompileSource(Module.scala:232)
	at scalaxb.compiler.wsdl11.Driver.buildCompileSource(Driver.scala:35)
	at scalaxb.compiler.Module$class.processReaders(Module.scala:223)
	at scalaxb.compiler.wsdl11.Driver.processReaders(Driver.scala:35)
	at scalaxb.compiler.Module$class.infoFiles(Module.scala:186)
	at scalaxb.compiler.wsdl11.Driver.infoFiles(Driver.scala:35)
	at scalaxb.compiler.Module$class.processFiles(Module.scala:165)
	at scalaxb.compiler.wsdl11.Driver.processFiles(Driver.scala:35)
	at sbtscalaxb.Plugin$ScalaxbCompile$$anonfun$sbtscalaxb$Plugin$ScalaxbCompile$$compile$1$1.apply(Plugin.scala:55)
	at sbtscalaxb.Plugin$ScalaxbCompile$$anonfun$sbtscalaxb$Plugin$ScalaxbCompile$$compile$1$1.apply(Plugin.scala:51)
	at scala.Option.map(Option.scala:145)
	at sbtscalaxb.Plugin$ScalaxbCompile$.sbtscalaxb$Plugin$ScalaxbCompile$$compile$1(Plugin.scala:51)
	at sbtscalaxb.Plugin$ScalaxbCompile$$anonfun$cachedCompile$1$1$$anonfun$apply$1.apply(Plugin.scala:60)
	at sbtscalaxb.Plugin$ScalaxbCompile$$anonfun$cachedCompile$1$1$$anonfun$apply$1.apply(Plugin.scala:59)
	at sbt.Tracked$$anonfun$outputChanged$1.apply(Tracked.scala:57)
	at sbt.Tracked$$anonfun$outputChanged$1.apply(Tracked.scala:52)
	at sbtscalaxb.Plugin$ScalaxbCompile$.apply(Plugin.scala:65)
	at sbtscalaxb.Plugin$$anonfun$baseScalaxbSettings$14.apply(Plugin.scala:90)
	at sbtscalaxb.Plugin$$anonfun$baseScalaxbSettings$14.apply(Plugin.scala:87)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by eed3si9n** [comment]
As the error message says, scalaxb expected `{http://schemas.xmlsoap.org/wsdl/}fault` but `{http://schemas.xmlsoap.org/wsdl/}documentation` was found.

Here's the definitions related to operation:

```xml
   <complexType name="documented" abstract="true">
      <sequence>
         <element ref="wsdl:documentation" minOccurs="0"/>
      </sequence>
   </complexType>

    <complexType name="startWithExtensionsType">
      <complexContent>
        <extension base="wsdl:documented">
        <sequence>
            <any namespace="##other" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
        </extension>
      </complexContent>
    </complexType>

<complexType name="binding_operationType">
      <complexContent>
   <extension base="wsdl:startWithExtensionsType">
   <sequence>
   <element name="input" type="wsdl:startWithExtensionsType" minOccurs="0"/>
   <element name="output" type="wsdl:startWithExtensionsType" minOccurs="0"/>
   <element name="fault" minOccurs="0" maxOccurs="unbounded">
     <complexType>
       <complexContent>
        <extension base="wsdl:startWithExtensionsType">
            <attribute name="name" type="NMTOKEN" use="required"/>
        </extension>
      </complexContent>
      </complexType>
   </element>
   </sequence>
   <attribute name="name" type="NCName" use="required"/>
   </extension>
  </complexContent>
</complexType>
```

In other words, XML is sensitive to the order in which the elements appear, and your operation definition needs to be in the following order:

1. wsdl:documentation
2. soap:operation
3. wsdl:input
4. wsdl:output
