### ISSUE TITLE
assertion failed: choice has no particles

### ISSUE THREAD

**Issue by FaKod** [eed3si9n/scalaxb#365]
With a quite complex XSD file (with a couple of includes, generated by XMLSpy), I get the exception below.
But as far I can see it, there are no empty choices.
What can I do to find the "wrong" XSD file and its line number f.e.?

```scala
(((scalaxb.ElemName(Some("http://otds-group.org/otds"), "ConditionalTags")) ^^ 
      (x => scalaxb.DataRecord(x.namespace, Some(x.name), scalaxb.fromXML[ConditionalTagConditionType](x, scalaxb.ElemName(node) :: stack)))) | 
      ((scalaxb.ElemName(Some("http://otds-group.org/otds"), "GroupedAbsolute")) ^^ 
      (x => scalaxb.DataRecord(x.namespace, Some(x.name), scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)))))
DEBUG [2016-01-14 07:38:14,182] xsd.Params: buildParam:  Param(Some(http://otds-group.org/otds),ImpactExecutionOrder,ReferenceTypeSymbol({http://otds-group.org/otds}ExecutionOrderEnum),Single,false,false,false,true)
DEBUG [2016-01-14 07:38:14,182] xsd.GenSource: makeCaseClassWithType: generateAccessors List(lazy val ImpactExecutionOrder = attributes("@ImpactExecutionOrder").as[ExecutionOrderEnum])
DEBUG [2016-01-14 07:38:14,182] xsd.Params: buildParam:  Param(Some(http://otds-group.org/otds),ImpactExecutionOrder,ReferenceTypeSymbol({http://otds-group.org/otds}ExecutionOrderEnum),Single,false,false,false,true)
DEBUG [2016-01-14 07:38:14,182] xsd.GenSource: makeCaseClassWithType: emitting DayImpact2
DEBUG [2016-01-14 07:38:14,182] xsd.Params: buildCompositorRef: Some(http://otds-group.org/otds) DayImpact2Option
DEBUG [2016-01-14 07:38:14,183] xsd.Params: buildParam:  Param(Some(http://otds-group.org/otds),dayimpact2option,XsDataRecord(ReferenceTypeSymbol({http://otds-group.org/otds}DayImpact2Option)),Single,false,false,false,false)
java.lang.AssertionError: assertion failed: choice has no particles: ChoiceDecl(Some(http://otds-group.org/otds),List(),1,1,1196)
	at scala.Predef$.assert(Predef.scala:165)
	at scalaxb.compiler.xsd.Parsers$class.buildChoiceParser(Parsers.scala:174)
	at scalaxb.compiler.xsd.GenSource.buildChoiceParser(GenSource.scala:31)
	at scalaxb.compiler.xsd.Parsers$class.buildCompositorParser(Parsers.scala:82)
	at scalaxb.compiler.xsd.GenSource.buildCompositorParser(GenSource.scala:31)
	at scalaxb.compiler.xsd.Parsers$class.buildElemParser(Parsers.scala:265)
	at scalaxb.compiler.xsd.GenSource.buildElemParser(GenSource.scala:31)
	at scalaxb.compiler.xsd.Parsers$class.buildParser(Parsers.scala:41)
	at scalaxb.compiler.xsd.GenSource.buildParser(GenSource.scala:31)
	at scalaxb.compiler.xsd.Parsers$class.buildParser(Parsers.scala:37)
	at scalaxb.compiler.xsd.GenSource.buildParser(GenSource.scala:31)
	at scalaxb.compiler.xsd.GenSource$$anonfun$17.apply(GenSource.scala:236)
	at scalaxb.compiler.xsd.GenSource$$anonfun$17.apply(GenSource.scala:236)
	at scala.collection.immutable.List.map(List.scala:273)
	at scalaxb.compiler.xsd.GenSource.makeCaseClassWithType(GenSource.scala:236)
	at scalaxb.compiler.xsd.GenSource.makeType(GenSource.scala:73)
	at scalaxb.compiler.xsd.GenSource$$anonfun$run$1.apply(GenSource.scala:52)
	at scalaxb.compiler.xsd.GenSource$$anonfun$run$1.apply(GenSource.scala:46)
	at scala.collection.immutable.List.map(List.scala:277)
	at scalaxb.compiler.xsd.GenSource.run(GenSource.scala:46)
	at scalaxb.compiler.xsd.Driver.generate(Driver.scala:55)
	at scalaxb.compiler.xsd.Driver.generate(Driver.scala:31)
	at scalaxb.compiler.Module$$anonfun$processImportables$1$1.apply(Module.scala:312)
	at scalaxb.compiler.Module$$anonfun$processImportables$1$1.apply(Module.scala:310)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at scalaxb.compiler.Module$class.processImportables$1(Module.scala:310)
	at scalaxb.compiler.Module$class.processCompileSource(Module.scala:353)
	at scalaxb.compiler.xsd.Driver.processCompileSource(Driver.scala:31)
	at scalaxb.compiler.Module$class.processReaders(Module.scala:206)
	at scalaxb.compiler.xsd.Driver.processReaders(Driver.scala:31)
	at scalaxb.compiler.Module$class.infoFiles(Module.scala:168)
	at scalaxb.compiler.xsd.Driver.infoFiles(Driver.scala:31)
	at scalaxb.compiler.Module$class.processFiles(Module.scala:147)
	at scalaxb.compiler.xsd.Driver.processFiles(Driver.scala:31)
	at scalaxb.compiler.Main$$anonfun$start$1.apply(Main.scala:53)
	at scalaxb.compiler.Main$$anonfun$start$1.apply(Main.scala:50)
	at scala.Option.foreach(Option.scala:257)
	at scalaxb.compiler.Main$.start(Main.scala:50)
	at scalaxb.compiler.SbtApp.run(SbtApp.scala:8)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.lang.AssertionError: assertion failed: choice has no particles: ChoiceDecl(Some(http://otds-group.org/otds),List(),1,1,1196)
```

**Comment by FaKod** [comment]
Uups, there was an empty choice...

```xml
		<xs:element name="DayImpact">
				<xs:complexType>
					<xs:choice/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
````

sorry...
