### ISSUE TITLE
Error with Logging Library during Compilation

### ISSUE THREAD

**Issue by michaelahlers** [eed3si9n/scalaxb#440]
I haven't gotten far with investigating it and I _assume_ the cause may be another SBT plugin's dependencies (so looking for guidance to confirm that or tips on resolving this).  Compilation fails with this error (from `last compile:scalaxb`):

```
java.lang.NoSuchFieldError: LINE_SEP
	at org.apache.log4j.pattern.LineSeparatorPatternConverter.<init>(LineSeparatorPatternConverter.java:47)
	at org.apache.log4j.pattern.LineSeparatorPatternConverter.<clinit>(LineSeparatorPatternConverter.java:34)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.log4j.pattern.PatternParser.class$(PatternParser.java:92)
	at org.apache.log4j.pattern.PatternParser.<clinit>(PatternParser.java:112)
	at org.apache.log4j.pattern.BridgePatternConverter.<init>(BridgePatternConverter.java:66)
	at org.apache.log4j.pattern.BridgePatternParser.parse(BridgePatternParser.java:46)
	at org.apache.log4j.EnhancedPatternLayout.<init>(EnhancedPatternLayout.java:480)
	at scalaxb.compiler.Log$Formatter.<init>(Log.scala:96)
	at scalaxb.compiler.Log$.configureLogger(Log.scala:87)
	at sbtscalaxb.ScalaxbCompile$$anonfun$sbtscalaxb$ScalaxbCompile$$compile$1$1.apply(ScalaxbCompile.scala:25)
	at sbtscalaxb.ScalaxbCompile$$anonfun$sbtscalaxb$ScalaxbCompile$$compile$1$1.apply(ScalaxbCompile.scala:23)
	at scala.Option.map(Option.scala:145)
	at sbtscalaxb.ScalaxbCompile$.sbtscalaxb$ScalaxbCompile$$compile$1(ScalaxbCompile.scala:23)
	at sbtscalaxb.ScalaxbCompile$$anonfun$cachedCompile$1$1$$anonfun$apply$1.apply(ScalaxbCompile.scala:32)
	at sbtscalaxb.ScalaxbCompile$$anonfun$cachedCompile$1$1$$anonfun$apply$1.apply(ScalaxbCompile.scala:31)
	at sbt.Tracked$$anonfun$outputChanged$1.apply(Tracked.scala:84)
	at sbt.Tracked$$anonfun$outputChanged$1.apply(Tracked.scala:79)
	at sbtscalaxb.ScalaxbCompile$.apply(ScalaxbCompile.scala:37)
	at sbtscalaxb.ScalaxbPlugin$$anonfun$baseScalaxbSettings$23.apply(ScalaxbPlugin.scala:41)
	at sbtscalaxb.ScalaxbPlugin$$anonfun$baseScalaxbSettings$23.apply(ScalaxbPlugin.scala:38)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (compile:scalaxb::scalaxbGenerate) java.lang.NoSuchFieldError: LINE_SEP
```

This occurs with version 1.5.2 of the plugin and SBT 0.13.15. I've tried other version combinations as well.

**Comment by michaelahlers** [comment]
Closing this. Going to work-around by isolating generated classes in a separate project with fewer plugins.
