### ISSUE TITLE
Pattern match is too strict for Dispatch version

### ISSUE THREAD

**Issue by eed3si9n** [eed3si9n/scalaxb#445]
### steps

Try using Dispatch 0.13.2.

### problem

Pattern match fails.

### expectation

We should default to some case.

**Comment by margussipria** [comment]
PR https://github.com/eed3si9n/scalaxb/pull/468 would help with released version, support for future major/minor combo can be added by using latest working template
```scala
      case (VersionPattern(_, _, _), async)                    =>
        generateDispatchFromResource(async, "/httpclients_dispatch0130")
```

**Comment by aleksandr-vin** [comment]
Also causes compilation error for 1.2.0 version of Dispatch:

```
scala.MatchError: (0.12.0,true) (of class scala.Tuple2)
        at scalaxb.compiler.wsdl11.Driver.generateRuntimeFiles(Driver.scala:204)
        at scalaxb.compiler.wsdl11.Driver.generateRuntimeFiles(Driver.scala:36)
        at scalaxb.compiler.Module$class.processCompileSource(Module.scala:355)
        at scalaxb.compiler.wsdl11.Driver.processCompileSource(Driver.scala:36)
        ...
```
