### ISSUE TITLE
StackOverflowError when invoking "scalaxb.fromXML"

### ISSUE THREAD

**Issue by polentino** [eed3si9n/scalaxb#496]
I'm using scalaxb to manipulate a quite complex XSD format for OpenADR (a standard for energy Demand Response): a copy of those XSD files can be fetched from [here](https://github.com/sangeeths/OpenADR/tree/master/openadr/schema/2.0/b) (you need all 14 of them). 

I wrote some tests to ensure the xml messages sent/received to/from an OpenADR server are correctly translated to the desired case classes, for example

```
"payload with oadrResponse" must "be converted into a OadrPayload containing a OadrResponseType object" in {

    val xml = <ns3:oadrPayload xmlns:ns14="urn:un:unece:uncefact:codelist:standard:5:ISO42173A:2010-04-07" xmlns:ns13="http://openadr
    .org/oadr-2.0b/2012/07/xmldsig-properties" xmlns:ns12="http://www.w3.org/2009/xmldsig11#" xmlns:ns11="http://www.w3.org/2000/09/xmldsig#"
                               xmlns:ns10="http://www.opengis.net/gml/3.2" xmlns:ns9="urn:ietf:params:xml:ns:icalendar-2.0:stream"
                               xmlns:ns8="urn:ietf:params:xml:ns:icalendar-2.0" xmlns:ns7="http://docs.oasis-open.org/ns/energyinterop/201110/payloads"
                               xmlns:ns6="http://www.w3.org/2005/Atom" xmlns:ns5="http://docs.oasis-open.org/ns/emix/2011/06/power" xmlns:ns4="http://docs
                               .oasis-open.org/ns/emix/2011/06/siscale" xmlns:ns3="http://openadr.org/oadr-2.0b/2012/07" xmlns:ns2="http://docs.oasis-open
                               .org/ns/emix/2011/06" xmlns:ns1="http://docs.oasis-open.org/ns/energyinterop/201110">
      <ns3:oadrSignedObject>
        <ns3:oadrResponse ns1:schemaVersion="2.0b">
          <ns1:eiResponse>
            <ns1:responseCode>452</ns1:responseCode>
            <ns1:responseDescription>Invalid ID</ns1:responseDescription>
            <ns7:requestID/>
          </ns1:eiResponse>
          <ns1:venID>VEN_123</ns1:venID>
        </ns3:oadrResponse>
      </ns3:oadrSignedObject>
    </ns3:oadrPayload>

    val payload = scalaxb.fromXML[OadrPayload](xml)
    payload mustBe a[OadrPayload]
    payload.oadrSignedObject.oadrsignedobjectoption.value mustBe a[OadrResponseType]
  }
```
the example above produces the expected results; however, if you try to run this test
```
  "payload with oadrCreatedPartyRegistration" must "be converted into a OadrPayload containing a OadrCreatePartyRegistrationType object" in {
    val xml = <ns3:oadrPayload xmlns:ns14="urn:un:unece:uncefact:codelist:standard:5:ISO42173A:2010-04-07" xmlns:ns13="http://openadr
    .org/oadr-2.0b/2012/07/xmldsig-properties" xmlns:ns12="http://www.w3.org/2009/xmldsig11#" xmlns:ns11="http://www.w3.org/2000/09/xmldsig#"
                               xmlns:ns10="http://www.opengis.net/gml/3.2" xmlns:ns9="urn:ietf:params:xml:ns:icalendar-2.0:stream"
                               xmlns:ns8="urn:ietf:params:xml:ns:icalendar-2.0" xmlns:ns7="http://docs.oasis-open.org/ns/energyinterop/201110/payloads"
                               xmlns:ns6="http://www.w3.org/2005/Atom" xmlns:ns5="http://docs.oasis-open.org/ns/emix/2011/06/power" xmlns:ns4="http://docs
                               .oasis-open.org/ns/emix/2011/06/siscale" xmlns:ns3="http://openadr.org/oadr-2.0b/2012/07" xmlns:ns2="http://docs.oasis-open
                               .org/ns/emix/2011/06" xmlns:ns1="http://docs.oasis-open.org/ns/energyinterop/201110">
      <ns3:oadrSignedObject>
        <ns3:oadrCreatedPartyRegistration ns1:schemaVersion="2.0b">
          <ns1:eiResponse>
            <ns1:responseCode>452</ns1:responseCode>
            <ns1:responseDescription>Invalid ID</ns1:responseDescription>
            <ns7:requestID>456789012876123</ns7:requestID>
          </ns1:eiResponse>
          <ns1:registrationID/>
          <ns1:venID/>
          <ns1:vtnID/>
          <ns3:oadrProfiles>
            <ns3:oadrProfile>
              <ns3:oadrProfileName>2.0a</ns3:oadrProfileName>
              <ns3:oadrTransports>
                <ns3:oadrTransport>
                  <ns3:oadrTransportName>simpleHttp</ns3:oadrTransportName>
                </ns3:oadrTransport>
                <ns3:oadrTransport>
                  <ns3:oadrTransportName>xmpp</ns3:oadrTransportName>
                </ns3:oadrTransport>
              </ns3:oadrTransports>
            </ns3:oadrProfile>
            <ns3:oadrProfile>
              <ns3:oadrProfileName>2.0b</ns3:oadrProfileName>
              <ns3:oadrTransports>
                <ns3:oadrTransport>
                  <ns3:oadrTransportName>simpleHttp</ns3:oadrTransportName>
                </ns3:oadrTransport>
                <ns3:oadrTransport>
                  <ns3:oadrTransportName>xmpp</ns3:oadrTransportName>
                </ns3:oadrTransport>
              </ns3:oadrTransports>
            </ns3:oadrProfile>
          </ns3:oadrProfiles>
          <ns3:oadrRequestedOadrPollFreq>
            <ns8:duration>PTS</ns8:duration>
          </ns3:oadrRequestedOadrPollFreq>
        </ns3:oadrCreatedPartyRegistration>
      </ns3:oadrSignedObject>
    </ns3:oadrPayload>

    val payload = scalaxb.fromXML[OadrPayload](xml)
    payload mustBe a[OadrPayload]
    payload.oadrSignedObject.oadrsignedobjectoption.value mustBe a[OadrCreatePartyRegistrationType]
  }
```
the test fails with this message:

> Cause: java.lang.StackOverflowError:
  at xxxx.XMLProtocol$class.fromAnySchemaTypeHelper1(xmlprotocol.scala:256)
  at xxxx.package$.fromAnySchemaTypeHelper1(xmlprotocol.scala:12)
  at xxxx.XMLProtocol$$anonfun$1.apply(xmlprotocol.scala:497)
  at xxxx.XMLProtocol$$anonfun$1.apply(xmlprotocol.scala:496)
  at xxxx.scalaxb.DataRecord$.fromAny(scalaxb.scala:493)
  at xxxx.scalaxb.DataRecord$.fromAny(scalaxb.scala:434)
  at xxxx.scalaxb.XMLStandardTypes$$anon$23.reads(scalaxb.scala:330)
  at xxxx.scalaxb.package$.fromXML(scalaxb.scala:17)
  at xxxx.XMLProtocol$class.fromAnySchemaTypeHelper2(xmlprotocol.scala:389)
  at xxxx.package$.fromAnySchemaTypeHelper2(xmlprotocol.scala:12)

Looks like scalaxb is stuck in an infinite loop when trying to parse the `registrationID` field, but I don't understand the reason why. Is there a way to get around the issue, or is it a bug in how scalaxb parses the xml?

**Comment by polentino** [comment]
Note: after further analysis, the error seems to be caused by a bug about how scalaxb parses elements that have a `substitutionGroup`. As a quick workaround, changing
```xml
<xs:element name="registrationID" substitutionGroup="ei:refID">
```
to
```xml
<xs:element name="registrationID" type="xs:string">
```
makes the parser to produce the expected result.

**Comment by MatthiasEckhart** [comment]
I experienced a similar issue. As a workaround, I just copied the content of the `substitutionGroup` into all referencing elements.
